server:
  port: 8000


spring:
  application:
    name: gateway

  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service  # Load balanced URI for the user service registered in Eureka
          predicates:
            - Path=/api/v1/user/**  # Route all requests to /user/** to the user service

        # You can add other routes here for additional services as needed.
        # - id: other-service
        #   uri: lb://other-service
        #   predicates:
        #     - Path=/other/**

    config:
      enabled: false


management:
  endpoint:
    health:
      probes:
        enabled: true
info:
  app:
    name: Gateway Service
    description: This service is responsible for Authorizing client requests.
    version: 1.0



eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/  # Eureka server URL
    fetch-registry: true  # Whether to fetch registry information from Eureka
    register-with-eureka: true